### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by ZKiteLM** [Yifang-Qin/DisenPOI#2]
可以分享一下raw_data吗？

**Comment by Yifang-Qin** [comment]
原文中使用的Tokyo和NYC数据集都在网络上有[公开下载](https://sites.google.com/site/yangdingqi/home/foursquare-dataset)方式，您也可以在我的另一个开源[repo](https://github.com/Yifang-Qin/Diff-POI/tree/main/data/raw)中找到raw_file，不过美团相关的数据集由于公司数据保密的要求无法公开，十分抱歉。
