### ISSUE TITLE
How did you train LSTPM?

### ISSUE THREAD

**Issue by wbcat132** [Yifang-Qin/DisenPOI#5]
LSTPM training data only has positive samples, how do you do negative sampling? I'm also doing AUC calculations now, please help me, thank you very much

**Comment by Yifang-Qin** [comment]
You can refer to the [utils/process_data.py](https://github.com/Yifang-Qin/DisenPOI/blob/main/utils/process_data.py), around line 100 to line 118. For DisenPOI, we generate one corresponding negative sample for each observed interactions by randomly sampling from the whole item set.
